package com.hotelbooking.model;
// default package
// Generated Nov 19, 2022, 5:18:30 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel")
public class Hotel implements java.io.Serializable {

	private Integer hotelId;
	private Category category;
	private Destination destination;
	private String hotelName;
	private String imageUrl;
	private String description;
	private String address;
	private Long price;
	private Integer rooms;
	private Integer availableRooms;
	private Set<Booking> bookings = new HashSet<Booking>(0);
	private Set<Rating> ratings = new HashSet<Rating>(0);

	public Hotel() {
	}

	public Hotel(Category category, Destination destination, String hotelName, String imageUrl, String description,
			String address, Long price, Integer rooms, Integer availableRooms, Set<Booking> bookings, Set<Rating> ratings) {
		this.category = category;
		this.destination = destination;
		this.hotelName = hotelName;
		this.imageUrl = imageUrl;
		this.description = description;
		this.address = address;
		this.price = price;
		this.rooms = rooms;
		this.availableRooms = availableRooms;
		this.bookings = bookings;
		this.ratings = ratings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Hotel_ID", unique = true, nullable = false)
	public Integer getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(Integer hotelId) {
		this.hotelId = hotelId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Category_ID")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Destination_ID")
	public Destination getDestination() {
		return this.destination;
	}

	public void setDestination(Destination destination) {
		this.destination = destination;
	}

	@Column(name = "Hotel_Name")
	public String getHotelName() {
		return this.hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	@Column(name = "Image_Url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "Description", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "Rooms")
	public Integer getRooms() {
		return this.rooms;
	}

	public void setRooms(Integer rooms) {
		this.rooms = rooms;
	}
	
	@Column(name = "Available_Rooms")
	public Integer getAvailableRooms() {
		return this.availableRooms;
	}

	public void setAvailableRooms(Integer availableRooms) {
		this.availableRooms = availableRooms;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "hotel", cascade = CascadeType.REMOVE)
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Rating> getRatings() {
		return this.ratings;
	}

	public void setRatings(Set<Rating> ratings) {
		this.ratings = ratings;
	}

}